<a href="https://colab.research.google.com/github/Rnov24/Rnov24/blob/main/2_1_Data_Manimpulation.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 2.1 Data Manipulation

## 2.1.1 Getting started

Untuk memulai, kita mememerlukan untuk mengimport library **Pytorch**, dengan catatan package-nya bernama `torch`

In [1]:
import torch

**Tensor** merepresentasikan array dari nilai numerik, jika hanya memiliki satu sumbu maka biasa didebut `Vector`, jika meiliki 2 sumbu maka disebut `Matrix`, jika memiliki $k > 2$ sumbu maka disebut juga $k^{th}$-ordo Tensor

In [3]:
x = torch.arange(12)
x

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

pada library `Pytorch` data type bawaan dari tensor adalah `float32`, berbeda dengan array pada `numpy` yang memiliki data type bawaan adalah `float64`.

In [5]:
import numpy as np

np_array = np.random.rand(12)

pt_tensor = torch.rand(12)

print("Numpy array dtype:", np_array.dtype)
print("Pytorch tensors dtype:", pt_tensor.dtype)

Numpy array dtype: float64
Pytorch tensors dtype: torch.float32


Kita bisa melihat jumlah elemen pada tensor dengan menggunakan `numel`

In [6]:
x.numel()

12

atau bisa dengan menggunakan `shape` untuk mengetahui lebih detail tentang bentuk dan dimensi dri tensor tersebut.

In [8]:
x.shape

torch.Size([12])

kita juga bisa merubah bentuk dari tensor tanpa mempengaruhi nilai yang ada didalamnya dengan menggunakan `reshape`.

In [9]:
X = x.reshape(3, 4)
X

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])

Perhatikan bahwa menentukan setiap komponen bentuk yang akan dibentuk ulang adalah hal yang mubazir. Karena kita sudah mengetahui ukuran tensornya, kita dapat mengerjakan satu komponen bentuk dengan mempertimbangkan komponen lainnya. contoh jika bentuk target adalah $(h, w)$ maka $w = \frac{N}{h}$. untuk melakukan invers pada tensor bisa ubah `-1` pada salah satu komponen bentuk target. dalam kasus kita, dari pada menggunakan `x.reshape(2, 4)`, kita bisa menggunakan `x.reshape(-1, 4)` atau `x.reshape(3, -1)`.


para praktisi biasanya memerlukan untuk membangun tensor yang hanya berisi 0 atau satu. untuk membangun tensor berelemen 0 kita hanya perlu memanggil `zeros` dan masukan bentuk yang kita inginkan sebagai argumen, contoh, (2, 3, 4).

In [10]:
torch.zeros((2, 3, 4))

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

sama juga untuk tensor bernilai 1, kita bisa membuatnya dengan `ones`

In [11]:
torch.ones((2, 3, 4))

tensor([[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]])

Kita sering kali ingin mengambil sampel setiap elemen secara acak (dan independen) dari distribusi probabilitas tertentu. Misalnya, parameter jaringan saraf sering kali diinisialisasi secara acak. Cuplikan berikut membuat tensor dengan elemen yang diambil dari distribusi standar Gaussian (normal) dengan mean 0 dan deviasi standar 1.

In [12]:
torch.randn(3, 4)

tensor([[-0.8024, -1.0762, -0.3228, -0.3029],
        [-0.0358,  1.4118,  1.0173,  1.7826],
        [ 0.2079, -3.1952,  0.5114, -1.0757]])

Terakhir, kita dapat membuat tensor dengan memberikan nilai yang tepat untuk setiap elemen dengan menyediakan daftar Python (mungkin bersarang) yang berisi literal numerik. Di sini, kita membuat matriks dengan daftar daftar, di mana daftar terluar berhubungan dengan sumbu 0, dan daftar dalam berhubungan dengan sumbu 1.

In [13]:
torch.tensor([[2, 1, 4, 3], [1, 2, 3, 4], [4, 3, 2, 1]])

tensor([[2, 1, 4, 3],
        [1, 2, 3, 4],
        [4, 3, 2, 1]])